image: archlinux
secrets:
  - c0d2aaa9-4e94-4d85-8ac9-259ab244bf3b
packages:
  - rsync
  - make
  - texlive-latexrecommended
  - texlive-fontsextra
  - texlive-latexextra
sources:
  - https://git.sr.ht/~acsqdotme/cv
tasks:
  - setup: |
      echo "setting up"
  - build: |
      cd cv
      make
  - deploy: |
      ssh-keyscan -H acsq.me >> ~/.ssh/known_hosts
      ssh-keyscan -H angelcastaneda.org >> ~/.ssh/known_hosts
      rsync -uvzP ~/cv/cv.pdf deploy@acsq.me:/var/www/acsq.me/static/files/cv.pdf
      rsync -uvzP ~/cv/cv.pdf deploy@angelcastaneda.org:/var/www/angelcastaneda.org/static/files/cv.pdf
