name: Ángel's Résumé CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install -y rsync make texlive-latex-extra texlive-fonts-extra

      - name: Make
        run: |
          make

      - name: Deploy with Rsync
        run: |
          echo ${{ secrets.DEPLOY_KEY }} > deploy_key
          chmod 600 ./deploy_key
          rsync -uvzP -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' cv.pdf deploy@angel-castaneda.com:/var/www/angel-castaneda.com/static/files/github-cv.pdf
