name: Ángel's Résumé CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install -y rsync make texlive-latex-extra texlive-fonts-extra

      - name: Compile TeX
        run: |
          make

      - name: SSH Setup
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: angel-castaneda.com

      - name: Known Host Trick
        run: ssh-keyscan -H angel-castaneda.com >> ~/.ssh/known_hosts

      - name: Deploy with Rsync
        run: |
          pwd
          rsync -uvzP cv.pdf deploy@angel-castaneda.com:/var/www/angel-castaneda.com/static/files/github-cv.pdf
